version: "3.7"

networks:
  autoscale:

configs:
  prometheus_config:
    file: ./prometheus.yml

services:
  autoscaler:
    image: buraketmen/docker-swarm-autoscaler:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - CPU_PERCENTAGE_UPPER_LIMIT=75
      - CPU_PERCENTAGE_LOWER_LIMIT=25
      - SLEEP_SECOND=30
    networks:
      - autoscale
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  cadvisor:
    image: google/cadvisor:v0.33.0
    networks:
      - autoscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus:v2.12.0
    networks:
      - autoscale
    command: ["--storage.tsdb.retention.size=1GB", "--config.file=/etc/prometheus/prometheus.yml", "--web.console.libraries=/etc/prometheus/console_libraries", "--web.console.templates=/etc/prometheus/consoles", "--web.enable-lifecycle"]
    configs:
       - source: prometheus_config
         target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
